host/greatfet/boards/azalea.py, host/greatfet/peripherals/i2c_bus.py, host/greatfet/peripherals/i2c_device.py, host/greatfet/peripherals/spi_flash.py, host/greatfet/sensor.py, host/greatfet/sensors/README, host/greatfet/sensors/tsl2561.py
Changes:
- Adds an easier-to-use I2C host API, which should make it fairly easy to hack on I2C devices.
- Adds a simple sensor API designed to make e.g. data-logging applications easy. This will be augmented in the future with a ```greatfet_datalog``` application, which will accept a list of sensors on the command line and produce e.g. nice real-time CSV output of sensor values. 
(Should not conflict with my other active PR.)
=> Add I2C host API (and stub sensor API).

firmware/common/i2c_lpc.c, firmware/greatfet_usb/usb_api_i2c.c
The changed to `i2c_lpc.c` should probably also be merged back into the HackRF source.
=> Fix I2C bus USB API

host/greatfet_adc, host/greatfet_flame, host/greatfet_sdir
I also uncommented the TX sleep.
=> SDIR RX typo fixes

host/greatfet_firmware
=> fix greatfet_firmware verbose help

host/greatfet/peripherals/spi_bus.py
=> SPI: Fix a totally WTF typo on my part.

firmware/README.md
=> Fix board string in firmware readme

host/greatfet_adc, host/greatfet_flame, host/greatfet_info, host/greatfet_logic, host/greatfet_sdir, host/greatfet_spiflash
Fixes various `NameError` exceptions caused by code using modules that were not imported.
=> Fix missing imports

host/setup.py
Install all `greatfet_*` commands so they are in the user's path.
=> Install all scripts in setup.py

firmware/common/greatfet_core.c, firmware/greatfet_usb/greatfet_usb.c
Default the LEDs to off in `greatfet_core` so each firmware doesn't have to turn them off.
=> Default LED state to off in pin_setup()

firmware/common/debug.h
=> Add #include guard in debug.h

host/greatfet/__init__.py, host/greatfet/boards/one.py, host/greatfet/boards/xplorer.py, host/greatfet/commands/greatfet_firmware.py, host/greatfet/commands/greatfet_info.py, host/greatfet/commands/greatfet_sdir.py, host/greatfet/commands/greatfet_spiflash.py, host/greatfet/peripherals/i2c_bus.py, host/greatfet/peripherals/i2c_device.py, host/greatfet/peripherals/spi_bus.py, host/greatfet/sensors/tsl2561.py
Remove imports for modules that are never used in the code.
=> Remove unused Python imports

host/greatfet/io_expander.py
Remove variables that are assigned but never used in the code.
=> Remove unused Python variables

host/greatfet/board.py
Instantiating a `GreatFET` object always fails on macOS Sierra.
Before this patch:
```
$ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from greatfet import GreatFET
>>> GreatFET()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/username/sandbox/git/GreatFET-experimental/host/greatfet/greatfet.py", line 50, in GreatFET
return GreatFETBoard.autodetect(**board_identifiers)
File "/Users/username/sandbox/git/GreatFET-experimental/host/greatfet/board.py", line 85, in autodetect
return subclass(**device_identifiers)
File "/Users/username/sandbox/git/GreatFET-experimental/host/greatfet/boards/one.py", line 48, …
```
=> Dispose resources to fix creating connection on macOS

firmware/greatfet_usb/usb_api_gpio.c
Allows GPIO output pins to be changed via USB.
=> Implement usb_vendor_request_write_gpio()

firmware/common/greatfet_core.h, firmware/greatfet_usb/greatfet_usb.c, firmware/greatfet_usb/usb_api_leds.c, firmware/greatfet_usb/usb_api_leds.h, host/greatfet/board.py, host/greatfet/boards/one.py, host/greatfet/boards/rad1o.py, host/greatfet/boards/xplorer.py, host/greatfet/peripherals/led.py, host/greatfet/protocol/vendor_requests.py
Just makes a nice little LED interface to be used from tools through the HAL (rather than through the GPIO interface)
=> Clean up LED interface

firmware/cmake/greatfet-common.cmake
for @dominicgs's yolo-merging pleasure
=> Support out-of-tree builds of GreatFET-derived firmware.

host/greatfet/commands/greatfet.py, host/setup.py
here's a somewhat-quickly thrown-together unified GreatFET command; whether or not we remove the subcommands from `setup.py` is TBD, though I'm leaning "should"
closes #102
=> host: add git-like single root "greatfet" command (#102)

firmware/common/i2c.h, firmware/common/i2c_bus.c, firmware/common/i2c_bus.h
And properly terminate a comment in i2c.h that was causing Wcomment
=> Fix i2c bus transfers not returning status

.editorconfig
Adding this as a simple start for editorconfig things. These settings roughly represent the existing settings in our projects.
I welcome discussion of these defaults -- or a quick merge. :)
=> all: add simple editorconfig to help with code style (#144)

.travis.yml, appveyor.yml, host/setup.py
Build on Linux and OS X.  The Linux builds test both python 2.7 and 3.6.
Experimental build artefacts are pushed to greatscottgadgets/nightly-build
=> Travis builds

host/greatfet/commands/greatfet_DS18B20.py, host/greatfet/commands/greatfet_adc.py, host/greatfet/commands/greatfet_adf7242.py, host/greatfet/commands/greatfet_dac.py, host/greatfet/commands/greatfet_logic.py, host/greatfet/commands/greatfet_msp430.py, host/greatfet/commands/greatfet_sdir.py, host/greatfet/commands/greatfet_spiflash.py, host/greatfet/examples/greatfet_flame, host/greatfet/glitchkit/base.py, host/greatfet/glitchkit/simple.py, host/greatfet/glitchkit/usb.py, host/greatfet/peripherals/i2c_bus.py, host/greatfet/peripherals/led.py, host/greatfet/peripherals/spi_bus.py
additional updates required by new comms api
=> Comms fixes

Makefile, firmware/flash_stub/CMakeLists.txt, firmware/greatfet_usb/CMakeLists.txt, host/MANIFEST.in, host/greatfet/__init__.py, host/greatfet/assets/.gitignore, host/greatfet/assets/README, host/greatfet/commands/greatfet_firmware.py, host/greatfet/utils.py, host/setup.py
There's a simple, convenience `Makefile` that may be somewhat controversial. I'm willing to drop it; it just makes things easy.
=> Automatically include firmware with the host tools, when possible [#208]

host/greatfet/commands/greatfet_logic.py
(cherry picked from commit 0aacfd4b0cc4c53530c40002942d6a880d88f434)
Resolves #213
=> add pulseview compatibility to the greatfet logic tool

host/greatfet/commands/greatfet_i2c.py, host/greatfet/peripherals/i2c_bus.py
=> i2c: scan at all three different i2c modes

firmware/greatfet_usb/classes/leds.c, host/greatfet/commands/greatfet_led.py, host/setup.py
I've tested everything except for the setup.py change (because of #227).
=> LED updates

host/setup.py
Fixes both our PEP compliance and issue #227.
=> host tools: fix our git-based versioning

host/README.md
It wasn't clear to me where these commands were supposed to be run from, so I added a small description.
I also removed a few commands that aren't needed.
=> Explain submodule install location and remove extra commands
