- host/greatfet/protocol/vendor_requests.py
This makes it much easier to add vendor requests before the end, as
each vendor request is based on the one before it. So only the request immediately after the added one has to change.
> Make adding vendor requests easier

- firmware/cmake/greatfet-common.cmake
- host/greatfet_firmware
- host/greatfet_logic
- host/greatfet_spiflash
Fixes three issues:
- ```m0_bin.s``` (autogenerated) ```incbin```s ```${PROJECT_NAME}_m0.bin```, but cmake isn't aware of the dependency. Add it explicitly to the target that assembles ```m0_bin.s```.
- Some of the ```print``` calls in the greatfet_* utilities were replaced with ```log_function```, even when it wasn't likely to be what we wanted; e.g. an error should always make it to the stderr, even if ```--verbose``` isn't on.
- ```greatfet_firmware``` shouldn't try to connect to a board when it doesn't have any commands to accomplish (e.g. when checking the help text).
> Build and tooling fixes. 

- firmware/greatfet_usb/usb_api_i2c.c
Once a USB connection is made, PLL1 is switched to 'max speed' at 204MHz;
but the current API incorrectly assumes PLL1 will be 48MHz, and selects too
low an I2C scaling factor accordingly.
This switches to the max_speed configuration appropriate for a PLL of 204MHz.
> Select proper clock for the USB I2C API.

- host/greatfet/io_expander.py
- host/greatfet/io_expanders/pca9674.py
- host/greatfet/io_expanders/pin.py
- host/greatfet/io_expanders/port.py
This adds an API for using IO Expanders and has an implementation for a PCA9674. This also has example implementations for different types hypothetical of IO expanders.
> Add API for IO Expanders

- firmware/greatfet_usb/greatfet_usb.c
- firmware/greatfet_usb/usb_api_adc.c
- firmware/greatfet_usb/usb_api_adc.h
This makes the list of vendor requests in the host code the same as in
the firmware. This way vendor requests can be added without problems.
> Add void read_adc vendor request

- firmware/common/greatfet_core.c
- firmware/common/usb.c
- firmware/greatfet_usb/usb_descriptor.c
- Correct the time and method of enumerating the FS USB PHY.
- As a temporary hack, lie to the PHY and tell it VBUS is always present.
- Fix an alignment issue on the USB1 endpoint list that broke all transactions.
> Fix issues that prevent USB1 from working.

- firmware/common/greatfet_pins.h
- firmware/common/spiflash_target.c
- firmware/common/xplorer_pins.h
- firmware/greatfet_usb/usb_api_spi.c
- host/greatfet/boards/xplorer.py
The LPC explorer has a different flash, and thus requires a slightly different setup. Also, fixes several places where <greatfet_pins.h> was used instead of <pins.h> and adds a couple of used SCU entries to <xplorer_pins.h> to make things build.
> Add flash support for LPC Xplorer

- firmware/README.md
Makes the process more clear for programming other boards, as we now apparently have a user trying to use the LPC Xplorer board as a Facedancer:
https://github.com/ktemkin/Facedancer/issues/1
> Add more detail to the firmware-loading readme.

- host/greatfet_firmware
The usage message would never be shown because any non-empty tuple is always truthy.
> Fix showing usage if no args are given

- host/greatfet_adc
`errno` [is used](https://github.com/dominicgs/GreatFET-experimental/compare/master...mnaberez:errno?expand=1#diff-aa87df1529eeeb0c137a6d07035e6c18R66) but not imported.
> Fix missing import for "errno"

- host/greatfet_firmware
Only two options had long names defined.  This adds long names for the rest.  `--reset` is especially useful since the short options `-r` (read) and `-R` (reset) may be confused.
> Add longopts for all options

- host/greatfet_firmware
I flashed custom firmware a few times but my changes didn't take effect.  I then realized that write does not imply reset so the target was still running the old firmware.  This change adds a message to hint that the target may need to be reset.
> Hint that new firmware won't run until reset

- firmware/blinky/blinky.c
Blinky already uses functions from `greatfet_core` like `led_on()` so use `delay()` from there too.
> blinky: Use delay() from greatfet_core

- host/greatfet_firmware
`greatfet_firmware` currently produces no output by default.  Since the program is normally run by people, not automation, having output by default is desirable.
Current behavior:
```
$ greatfet_firmware --write foo.bin
$
$ greatfet_firmware --write foo.bin --verbose
Trying to find a GreatFET device...
GreatFET One found. (Serial number: abc123)
Writing data to SPI flash...
Written 1048576 bytes of 1048576.
Write complete!
Reset not specified; new firmware will not start until next reset.
$
```
After this change:
```
$ greatfet_firmware --write foo.bin
Trying to find a GreatFET device...
GreatFET One found. (Serial number: abc123)
Writing data to SPI flash...
Written 1048576 bytes of 1048576.
Write complete!
Reset not specified; new firmware will not start until next reset.
$
$ …
```
> Replace --verbose with --quiet and default to not quiet

- host/greatfet_adc
- host/greatfet_info
- host/greatfet_logic
- host/greatfet_sdir
- host/greatfet_spiflash
Replaces:
```
if __name__ == '__main__':
... code ...
```
with:
```
def main():
... code ...
if __name__ == '__main__':
main()
```
This will allow the scripts to be eventually called via an [entry point](http://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point).
> Wrap loose code in main()

- host/greatfet/commands/greatfet_info.py
`greatfet_info` should only show info about the GreatFET, it shouldn't change the GreatFET's state.  The user may have programmed the LEDs and changing them will be unexpected.
> Remove LED side effect from greatfet_info

- host/greatfet/commands/greatfet_info.py
`if not device` would never be reached because `GreatFET()` ctor throws `DeviceNotFoundError`.
> Fix error message for missing GreatFET

- firmware/greatfet_usb/greatfet_usb.c
- firmware/greatfet_usb/usb_api_gpio.c
- firmware/greatfet_usb/usb_api_gpio.h
The `gpio_monitor_mode` task doesn't appear to serve any necessary function anymore but it interferes with the user's ability to control the LEDs.  Let's remove it.
> Remove nonfunctional gpio_monitor_mode

- firmware/greatfet_usb/usb_api_adc.c
- firmware/greatfet_usb/usb_api_gpio.c
- firmware/greatfet_usb/usb_api_i2c.c
- firmware/greatfet_usb/usb_api_logic_analyzer.c
- firmware/greatfet_usb/usb_api_sdir.c
- firmware/greatfet_usb/usb_api_spi.c
Tasks change the LEDs in seemingly random ways, which are probably artifacts from debugging.  In order to allow the user to control the LEDs, tasks shouldn't change them.
> Remove LED changes used for debugging

- firmware/greatfet_usb/CMakeLists.txt
- firmware/greatfet_usb/greatfet_usb.c
- firmware/greatfet_usb/usb_api_heartbeat.c
- firmware/greatfet_usb/usb_api_heartbeat.h
- host/greatfet/protocol/vendor_requests.py
This change moves the heartbeat LED blink code into a task that can be started/stopped using vendor requests.  The task is running by default.
```
>>> from greatfet import GreatFET
>>> from greatfet.protocol import vendor_requests
>>> device = GreatFET()
>>> device.vendor_request_out(vendor_requests.HEARTBEAT_STOP)
0
>>> device.vendor_request_out(vendor_requests.HEARTBEAT_START)
0
```
The use case for this change is to allow the user to control all of the onboard LEDs.  Currently, the heartbeat code always has control of LED1.
> Move heartbeat to a task that can be started and stopped

- firmware/greatfet_usb/CMakeLists.txt
- firmware/greatfet_usb/greatfet_usb.c
- firmware/greatfet_usb/usb_api_leds.c
- firmware/greatfet_usb/usb_api_leds.h
Move `usb_vendor_request_led_toggle()` to a separate `usb_api_` file for parity with the other USB request handlers.
> Move LED request handler to its own file

- firmware/common/debug.c
- firmware/common/debug.h
- firmware/greatfet_usb/CMakeLists.txt
This patch resurrects 8d29f4446b9330da0a059a3145514e3809b6b59e with some changes to the UART settings and API.  It allows logging debug messages out UART2 like this:
```
// 9600-N-8-1, TX on P7_1, RX on P7_2
debug_init();
debug_log("foo\n");
debug_log("bar\n");
```
I've tested this using an FTDI [TTL-232R-3V3](https://www.digikey.com/product-detail/en/ftdi-future-technology-devices-international-ltd/TTL-232R-3V3/768-1015-ND/1836393) under Linux with minicom and it worked fine.  This patch is transmit-only but I've also tested [`uart_read`](https://github.com/dominicgs/libopencm3/blob/1c45abedbce49fe179030287325baf91f7e0d5e1/lib/lpc43xx/uart.c#L182) and receive worked also.
> Add debug functions to send messages out UART2

- firmware/common/greatfet_core.c
- firmware/common/greatfet_core.h
- firmware/greatfet_usb/greatfet_usb.c
- firmware/greatfet_usb/usb_api_heartbeat.c
The GreatFET firmware sits in a [busy loop](https://github.com/dominicgs/GreatFET-experimental/blob/e390a01bd1776394987ab401a31a3c0dfc8e5d0c/firmware/greatfet_usb/usb_api_heartbeat.c#L31-L32
) for 1 second on every iteration of the main loop so it can blink the heartbeat LED.  No meaningful processing can be done in the main loop (e.g. servicing a queue filled by an ISR) because the main loop blocks for so long doing nothing.
This change replaces the busy loop with polling the RTC seconds register.  The heartbeat LED blinks as before but it doesn't block the main loop.  Polling is used instead of an ISR so that the LED will stop blinking if the main loop gets stuck, as it did before, which is useful for debugging.
> Make heartbeat nonblocking by polling RTC

- firmware/common/debug.c
- firmware/greatfet_usb/greatfet_usb.c
GreatFET starts up in with PLL1 in low speed and then switches to high speed after USB enumeration completes.  The libopencm3 functions set up the UART clock to be derived from PLL1, and the [debug UART functions](https://github.com/dominicgs/GreatFET-experimental/blob/3b0a3f171af7bcecaa4a6401ecdd194afdfc7e55/firmware/common/debug.c#L34-L37) assumes PLL1 is high speed.  If you use the debug UART functions before USB is ready, the UART output will be garbled because the settings are wrong for PLL1 low speed.  This change leaves PLL1 in high speed mode all the time to fix this.
> Always run PLL1 at max speed

- host/greatfet/io_expanders/pin.py
`value` isn't defined in this context; only `pin_num` can be validated.
> Fix undefined name 'value'

- host/greatfet/errors.py
`GREATFET_ERRORS` is a `dict`, which has a `get()` method for getting the value or a default.
> Use dict.get() for default value

- firmware/common/greatfet_core.h
```
$ grep -r 1v8 *
firmware/common/greatfet_core.h:void enable_1v8_power(void);
firmware/common/greatfet_core.h:void disable_1v8_power(void);
$
```
These declarations are [leftovers from HackRF](https://github.com/mossmann/hackrf/blob/44333b76359de2856de9eca4052758eb733ab085/firmware/common/hackrf_core.c#L843-L849).
> Remove HackRF 1.8v control artifacts

- firmware/blinky/blinky.c
Developers will probably use Blinky as the starting point for writing their first GreatFET firmware.  Some core functions [like debug](https://github.com/dominicgs/GreatFET-experimental/blob/16c66249648f2762669fce72069fbd0a9f240ddd/firmware/common/debug.c#L34-L39) depend on PLL1 being set to max speed.  This patch adds that setup to Blinky to avoid confusion when developers try to use `debug_log()` and similar functions that depend on specific PLL1 settings.
> Initialize clock during Blinky setup

- host/greatfet/peripherals/gpio.py
This change is for documentation.  It wasn't clear to me what these magic numbers were until I read through the USB code in the firmware.
> Add _gpio() function to document magic numbers

- firmware/greatfet_usb/usb_api_gpio.c
- host/greatfet/peripherals/gpio.py
This patch fixes `usb_vendor_request_register_gpio()` so that the pin directions can be configured.  It also adds comments to explain the packet format since there is no host code yet to demonstrate it.
> Fix GPIO pin directions not being configured

- firmware/greatfet_usb/greatfet_usb.c
- firmware/greatfet_usb/usb_api_spiflash.c
- firmware/greatfet_usb/usb_api_spiflash.h
- host/greatfet/peripherals/spi_flash.py
- host/greatfet/protocol/vendor_requests.py
Consistency with other vendor request groups (cf. `I2C_`, `SPI_`, `ADC_`, `SDIR_`, `GREATDANCER_`, etc).
> Use a common "SPIFLASH_" prefix for flash vendor requests

- firmware/greatfet_usb/greatfet_usb.c
- firmware/greatfet_usb/usb_api_gpio.c
- firmware/greatfet_usb/usb_api_gpio.h
- host/greatfet/protocol/vendor_requests.py
Currently, there is no way for the host to interrogate previous GPIO registrations that have been made.  Until that is implemented, provide a way to reset the registrations as a way for the host to resynchronize with the state of the GreatFET.
> Add vendor request to clear GPIO registrations

- firmware/common/gpio_scu.c
- firmware/common/gpio_scu.h
- firmware/greatfet_usb/CMakeLists.txt
- firmware/greatfet_usb/usb_api_gpio.c
For a pin to be used as GPIO, it must be configured for GPIO mode in the SCU pinmux registers.  The USB GPIO API does not do this.  Some pins will happen to work because they need `SCU_PINMUX_CONF_FUNCTION0` (the default) but pins that require a different setting will not work.
This change configures the pinmux whenever a pin is registered with the USB GPIO API.  
Configuring the pinmux requires an LPC pin constant (e.g. `P4_3`) and the SCU function to set GPIO mode (e.g. `SCU_PINMUX_CONF_FUNCTION0`).  The USB GPIO API does not have these available; it only has the GPIO port and bit (`GPIO2[3]`).  New functions were added to perform these lookups since this functionality doesn't seem to exist in `libopencm3`.  The functions were added to GreatFET common instead of `libopencm3` because …
> Configure SCU pinmux to set lines as GPIO

- firmware/greatfet_usb/greatfet_usb.c
- firmware/greatfet_usb/usb_api_gpio.c
- firmware/greatfet_usb/usb_api_gpio.h
- host/greatfet/protocol/vendor_requests.py
This change adds a new vendor request so the host can read GPIO lines that have been registered as inputs.  It always returns the state of all inputs.  Each GPIO input line is one bit, so the data packet contains one byte for every eight GPIO inputs.
> Add vendor request to read GPIO inputs

- host/greatfet/boards/one.py
- host/greatfet/peripherals/gpio.py
This adds new functions to the host code so individual GPIO lines can be controlled.
Toggle output `J1.P3`:
```
from greatfet import GreatFET 
from greatfet.peripherals.gpio import J1, Directions
gf = GreatFET()
gf.gpio.setup(J1.P3, Directions.OUT)
state = True
while True:
gf.gpio.output(J1.P3, state)
state = not state
```
Read input `J1.P3` and set output `J1.P5`:
```
from greatfet import GreatFET 
from greatfet.peripherals.gpio import J1, Directions
gf = GreatFET()
gf.gpio.setup(J1.P3, Directions.IN)
gf.gpio.setup(J1.P5, Directions.OUT)
while True:
state = gf.gpio.input(J1.P3)
gf.gpio.output(J1.P5, state)
```
- Firmware has no support for reading the GPIO configuration.  In order to synchronize with the state of the GreatFET, this code must reset the GreatFET's GPIO state.  This should …
> Add support for controlling GPIO from host code

- host/greatfet/commands/greatfet_spiflash.py
Need to increment by 256 rather than 255 to make the address of the next
block the address after the end of the current one. This fixes a bug
where the last byte of a block is always repeated as the first byte of
the next.
> Fix off by one in spi dump

- firmware/README.md
The firmware build instructions are broken. CMake doesn't automatically create a target by the same name of the project, so `greatfet_usb` is not a target generated by CMake.
> Fix firmware build documentation

- firmware/greatfet_usb/usb_api_spi.c
- host/greatfet/peripherals/spi_bus.py
I'm not really into python, so not sure if there is any other better way around to define the frequency presets. Let me know if there is any other better approach and you want me to change the code.
I defined the spi frequencies inside `spi_bus.py` cause I'm assuming that only LPC43xx boards will be supported, otherwise these frequencies should be defined per board instead.
> Some changes to SPI bus frequency code

- firmware/common/usb_type.h
Using `#pragma GCC diagnostic ignored "-Wpacked-not-aligned"` generates a warning on older versions of GCC as `Wpacked-not-aligned` wasn't a thing until newer versions.
> Remove warning about non-existent error on older versions of GCC

- firmware/common/debug.c
- firmware/common/greatfet_core.c
- firmware/common/time.c
- firmware/common/time.h
- firmware/common/timers.h
For hardware verification / diagnosis of slow startups, we now track the time it takes to start the main oscillator and to switch to each of its PLLs.
```
[           0] GreatFET started!
[           4] Bootstrapping the system clock off of the external 12MHz oscillator.
[        6131] External oscillator bringup complete (took 5844 uS).
[        6396] Switching the system clock to PLL1 at 48MHz.
[        8087] Clock switch complete (took 1470 uS).
[        8188] Switching the system clock to PLL1 at 204MHz.
[        9743] Clock switch complete (took 1499 uS).
[        9757] Configuring board pins...
[        9769] Board advertises an RTC. Bringing it up...
[      574424] RTC bringup complete (took 564642 uS).
```
> Firmware: track more oscillator/PLL timings

- firmware/README.md
The LPC4330 manual (https://www.nxp.com/docs/en/user-guide/UM10503.pdf) specifies SPI boot as the pins being set to 7 (in figure 16) but instructions incorrectly have all the switches backwards.
Closes #152
> Fix flashing instructions for LPC Xplorer

- host/greatfet/board.py
- libgreat/firmware/drivers/comms/comms_class.c
- libgreat/firmware/drivers/comms/core.c
- libgreat/firmware/drivers/comms/utils.c
- libgreat/firmware/drivers/usb/comms_backend.c
- libgreat/firmware/drivers/usb/lpc43xx/usb.c
- libgreat/firmware/drivers/usb/lpc43xx/usb_queue.c
- libgreat/firmware/include/drivers/comms.h
- libgreat/firmware/include/drivers/usb/lpc43xx/usb_queue.h
This suite of commits provides the foundation for a number of changes to come over the next few days. Primarily, it should dramatically increase the stability of USB communications -- allowing communications to resume even in the event of an error that 'breaks the state' of the USB connection.
This is especially nice, as we can e.g. run `greatfet dmesg` even after a USB request handler fails to execute properly or times out.
> USB and communications fixes

- libgreat/host/pygreat/comms_backends/usb.py
This fixes #186 by padding serial numbers before passing them to pyUSB.  It does not pad them for other comms backends (of which we have none right now).
> Pad serial numbers to 32 character for passing to pyUSB

- libgreat/host/pygreat/board.py
- libgreat/host/pygreat/classes/core.py
It seems sensible to return the part ID the same way that we return the serial number, so that's what this does.  It removes the python 2 workaround in `_to_hex_string()`
Fixes #185 by removing the need for `future.builtins`
There may be unforeseen consequences if this, so I'm asking @ktemkin for review.
> Return part ID as ints, matchesi the way we handle serials

- firmware/greatfet_usb/classes/glitchkit/usb.c
- host/greatfet/commands/greatfet_shell.py
- host/greatfet/glitchkit/usb.py
- libgreat/firmware/drivers/comms/utils.c
- libgreat/firmware/drivers/usb/lpc43xx/usb_queue_host.c
- libgreat/firmware/include/drivers/comms.h
This addresses most of @mossmann's commentary in #92:
- Failures don't block the host GreatFET.
- Added an option to disable VBUS afterwards.
- Further improvements to system stability to enhance the user's experience.~
> glitchkit: try to handle USB failures in a more friendly way

- firmware/common/greatfet_core.c
- firmware/common/i2c_bus.c
- firmware/common/i2c_bus.h
- firmware/common/i2c_lpc.c
- firmware/common/i2c_lpc.h
- firmware/greatfet_usb/classes/i2c.c
- host/greatfet/boards/one.py
- host/greatfet/commands/greatfet_i2c.py
- host/greatfet/peripherals/i2c_bus.py
- host/greatfet/peripherals/i2c_device.py
i2c: move scan to firmware, fix 7 vs 8-bit address issues, split transfer into separate read/write functions, implement table output for scan
> i2c: scan/read/write improvements

- host/setup.py
`python setup.py install` was failing with `FileNotFoundError` due to this.
> Host: setup.py: fix `long_description` to use README.md instead of README

- host/greatfet/utils.py
This should fix #226, which occurs due to python2's overly permissive
PATH-scheme.
> host: py2 compat: switch to relative imports in greatfet.utils

- host/greatfet/commands/gf.py
On Windows, execv returns when the child process *starts*. The intended behavior is it to return when the process *ends*.
Issue described here: https://bugs.python.org/msg198599
**I have not tested that this change has the correct behavior on linux**
Before this fix on Windows, the `greatfet` command would return, then run the subcommand in the  background:
After this change on Windows, `greatfet` doesn't return until the subcommand is complete (matches linux behavior):
> Return once the child process *ends* (windows bug fix)
